---
title: "R package development workshop"
---

Welcome to the R package development workshop!

The modules use materials originally developed by [Forwards](https://forwards.github.io), 
the taskforce for underrepresented groups in the R community. 
I adapted and updated the material and [taught it for three years at The University of Warwick](https://warwick-stats-resources.github.io/courses.html#r-package-development-june-2025),
then [taught the course again for Forwards](https://forwards.github.io/package-dev) in June/July 2025, as part of the Forwards teaching team.
This iteration of the course builds on that latest version for Forwards.

## Syllabus overview

This is a hands-on workshop consisting of five modules, covering the entire process of creating an R package: functions and data, checking and testing, all levels of documentation, publication and maintenance. 

The material is based on the book *R Packages (2nd edition)* by Hadley Wickham and Jennifer Bryan. 
It is [freely availble online](https://r-pkgs.org).

All slides and further resources can be accessed from the [modules](modules.qmd) page.

## Prerequistes

Please see the [prerequisites](prerequisites.qmd) page for details on getting set up in advance of the first module.

## Instructor

The workshop is taught by [Ella Kaye](https://ellakaye.co.uk).